name: Go-build

on:
    pull_request:
      branches: [ "main" ]
      
jobs:
  go-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - run: go version
      - name: Install Dependencies
        run: go get .
      - name: Build binary
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o webapp main.go
      - name: Copy Go binary to Packer directory
        run: |
          rm -f ./packer/webapp
          cp ./webapp ./packer/